In [1]:
import pandas as pd

In [5]:
#Creating data 
pd.DataFrame({'Yes':[50,21],'No':[130,23],'May be':[0,0]})

   Yes   No  May be
0   50  130       0
1   21   23       0

In [7]:
pd.DataFrame({'Suzy':['I love it!','So good'], 'Mac':['tried','Can be better']},index = ['A','B'])

         Suzy            Mac
A  I love it!          tried
B     So good  Can be better

In [9]:
#From Series 
pd.Series([1,2,3,4,5], index = ['Prod A','Prod B','Prod C','Prod D','Prod E'])

Prod A    1
Prod B    2
Prod C    3
Prod D    4
Prod E    5
dtype: int64